name: CD

run-name: Update repo (${GITHUB_SHA::7})

on:
  workflow_call:

jobs:
  update_repo:
    runs-on: ubuntu-latest
    steps:
      - name: ☁️ Retrieve repo
        uses: actions/checkout@v3

      - name: ☁️ Configure, commit and push
        run: |+
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add . || true
          git commit -m "[dot_mngr] update repo" || true
          git status && git push || true
